CREATE TABLE TBL_USUARIOS (
  USU_ID int NOT NULL AUTO_INCREMENT,
  USU_NOMBRE varchar(20) NOT NULL,
  USU_CORREO varchar(20) NOT NULL,
  PRIMARY KEY (USU_ID)
);

CREATE TABLE TBL_ACCESOS (
  ACC_ID int NOT NULL AUTO_INCREMENT,
  ACC_PASS varchar(20) NOT NULL,
  ACC_USU varchar(20) NOT NULL,
  PRIMARY KEY (ACC_ID)
);

CREATE TABLE TBL_RELACIONES (
  REL_ID int NOT NULL AUTO_INCREMENT,
  USU_ID int NOT NULL,
  ACC_ID int NOT NULL,
  PRIMARY KEY (REL_ID),
  FOREIGN KEY (USU_ID) REFERENCES TBL_USUARIOS(USU_ID),
  FOREIGN KEY (ACC_ID) REFERENCES TBL_ACCESOS(ACC_ID)
);

